name: Publish Release
on:
  push:
    tags:
      - v*.**.**

env:
  GPG_KEY_ID: ${{ secrets.SIGN_KEY_ID }}
  GPG_SECRET_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  GPG_PASSWORD: ${{ secrets.SIGN_PASS }}
  OSSRH_USER: ${{ secrets.OSS_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.OSS_PASSWORD }}
  GRADLE_OPTS: "-Xmx4G -Xms4G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8"

jobs:
  run-test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      # 检出仓库代码
      - name: Check Out Repo
        uses: actions/checkout@v3

      # setup Java
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      # setup Gradle
      - name: Gradle Publish Release
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          arguments: clean assemble build test

  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: run-test
    steps:
      # 检出仓库代码
      - name: Check Out Repo
        uses: actions/checkout@v3

      # setup Java
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      # the gpg
      - name: Decode gpg file
        id: decode-gpg-file
        run: |
          mkdir -p ~/.gradle
          echo "${{ secrets.GPG_B64 }}" > ~/.gradle/secring.gpg.b64
          base64 -d ~/.gradle/secring.gpg.b64 > ~/.gradle/secring.gpg
          echo "::set-output name=SEC_KEY_RING_FILE::$(echo ~/.gradle/secring.gpg)"

      # setup Gradle
      - name: Gradle Publish Release
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          arguments: clean build publishArchetypePublicationToSonatypeRepository closeAndReleaseStagingRepository --warning-mode all --info -Porg.gradle.jvmargs="org.gradle.jvmargs=-Xmx4G -Xms4G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8"
        env:
          SIMBOT_IS_SNAPSHOT: false
          SIMBOT_RELEASES_ONLY: true
          SIMBOT_SNAPSHOT_ONLY: false

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: publish-release
    permissions:
      contents: write
    steps:
      # 检出仓库代码
      - name: Check Out Repo
        uses: actions/checkout@v3

        # Create gitHub release
      - name: Create Github Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          token: ${{ secrets.PUSH_TOKEN }}
#          body_path: .changelog/${{ github.ref_name }}.md
          generate_release_notes: true
          prerelease: ${{ contains(github.ref_name, 'preview') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') }}



